### ISSUE TITLE
Speed up travis builds by using a cache for the maven repository

### ISSUE THREAD

**Issue by p013570** [gchq/Gaffer#471]
Something like:

```yml
cache:
  directories:
  - $HOME/.m2
```

See https://docs.travis-ci.com/user/caching/
